##
url: https://mryang1688.github.io #the base hostname & protocol for your site e.g.
baseurl: /
title: Qi's Blog
description: > #this means to ignore newlines until "nav_lists:"
    Yang Xiao's Blog | 杨校的博客

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /blog/about.html

paths:
  base: /blog
  home: /
  all:  /blog/all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: mryang1688/mryang1688.github.io
repository_tree: master

## Language & timezone ##
lang: zh #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai

## Author & social ##
author:
  name: "Yang Xiao"
  email: mryang@mingyang888.cn
  # facebook:  #your Facebook username
  twitter: mryang1688
  github:  mryang1688
  googleplus: 101827554735084402671
  weibo: 234695683
  douban: mryang1688
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
  shortname: mryang1688-github-io #the Disqus shortname for the site

## Google Analytics ##
ga_tracking_id: UA-71907556-1 #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
  app_key: Mzf5m9skSwYVWVXhGiYMNyXs
  app_class: ThomasBlog

# mathjax: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
port: 4001