title: Yang Xiao
description: My Personal Blog
author: Yang Xiao
logo: /static/img/avatar.png
github: https://github.com/mryang1688
about: Java Teacher

baseurl: "https://mryang1688.github.io/hcz-jekyll-blog"
url: "https://mryang1688.github.io/hcz-jekyll-blog"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
