title:Yang Xiao
description: My Personal Blog
author: Yang Xiao
logo: http://mryang1688.github.io/static/img/avatar.png
github: https://github.com/mryang1688/mryang1688.github.io
about: Java Teacher

baseurl: "https://codeasashu.github.io/hcz-jekyll-blog"
url: "https://codeasashu.github.io/hcz-jekyll-blog"

allowsearch: true

disqus_shortname: about
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
#permalink: /:categories/:year/:month/:day/:title 